language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install coveralls
  - pip install flake8

# command to run tests
script:
  - flake8 . --exclude=__init__.py
  - nosetests -v --with-coverage --cover-tests

after_success:
  - coveralls
